const path=location.pathname.replace(/\/$/,'')||'/';
const photo=(label,extra='')=>`<div class="photo ${extra}" data-label="${label}" role="img" aria-label="${label}"></div>`;
const clientGallery='https://clientes.castastudio.pt';
const christmasBooking='https://castafotografia.pixieset.com/booking';
const nav=()=>`<div class="nav-reveal-zone" aria-hidden="true"></div><header class="nav"><a class="brand brand-logo" href="/historias" aria-label="CASTA Histórias"><img src="/assets/casta-logo-black.png" alt="CASTA"></a><nav class="links" id="links"><a href="/historias/casamentos">Casamentos</a><a href="/historias/maternidade">Maternidade & Família</a><a href="/historias/batizados">Batizados</a><a href="${christmasBooking}" target="_blank" rel="noopener noreferrer">Natal · Reservar ↗</a><a href="${clientGallery}" target="_blank" rel="noopener noreferrer">Galerias de Clientes ↗</a><a href="/historias/sobre">Sobre Nós</a><a href="/historias/contacto">Contacto</a></nav><button class="menu" aria-expanded="false" aria-controls="links" aria-label="Abrir menu">MENU</button></header>`;
const footer=()=>`<footer class="footer"><div><h3>CASTA Studio</h3><div>Fotografia & Filme<br>Alenquer, Portugal</div></div><div><span class="eyebrow">Contacto</span><p><a href="/historias/contacto">Falar connosco</a><br><a href="https://wa.me/351919592819" target="_blank" rel="noopener noreferrer">WhatsApp Histórias</a><br><a href="https://www.instagram.com/castafotografia/" target="_blank" rel="noopener noreferrer">Instagram Histórias</a></p></div><div><span class="eyebrow">Acesso rápido</span><p><a href="${clientGallery}" target="_blank" rel="noopener noreferrer">Galerias de Clientes ↗</a><br><a href="/comercial">CASTA Comercial →</a></p></div></footer>`;
const commercialFooter=()=>`<footer class="footer dark"><div><h3>CASTA Studio</h3><div>Fotografia & Vídeo<br>Alenquer, Portugal</div></div><div><span class="eyebrow">Contacto Comercial</span><p><a href="/comercial/contacto">Falar connosco</a><br><a href="https://wa.me/351913415383" target="_blank" rel="noopener noreferrer">WhatsApp Comercial</a><br><a href="https://www.instagram.com/casta.pro/" target="_blank" rel="noopener noreferrer">Instagram Comercial</a></p></div><div><span class="eyebrow">Outro universo</span><p><a href="/historias">CASTA Histórias →</a></p></div></footer>`;
const cta=(title,button,href)=>`<section class="cta"><h2>${title}</h2><p>Contem-nos o que estão a planear e verificamos disponibilidade.</p><a class="btn" href="${href}">${button}</a></section>`;
const gallery=(labels=['Casamento','Família','Newborn','Batizado','Momentos'])=>`<div class="gallery">${labels.map(x=>photo(x)).join('')}</div>`;
const prices=(items)=>`<section class="section price-section"><span class="eyebrow">Valores de referência</span><h2>Para começarem a planear.</h2><div class="price-grid">${items.map(([name,price,note])=>`<article><h3>${name}</h3><strong>desde ${price}</strong>${note?`<p>${note}</p>`:''}</article>`).join('')}</div><p class="price-note">Cada história é diferente. Confirmamos disponibilidade, deslocações e a opção mais adequada antes da reserva.</p></section>`;
const testimonials=(items)=>`<section class="section testimonials"><span class="eyebrow">Palavras de quem já esteve connosco</span><h2>Experiências reais.</h2><div class="testimonial-grid">${items.map(([quote,name,context])=>`<blockquote><div class="stars" aria-label="5 estrelas">★★★★★</div><p>“${quote}”</p><footer><strong>${name}</strong>${context?`<span>${context}</span>`:''}</footer></blockquote>`).join('')}</div></section>`;
const weddingReviews=[['Incríveis desde o primeiro momento. Super prestáveis, simpáticos e acolhedores. Toda a gente os adorou.','Daniela S.','Casamento'],['Muito profissionais desde o primeiro contacto. Conseguiram captar a nossa história de amor no estilo que queríamos. Recomendamos!','Cliente CASTA','Casamento bilingue'],['Muito à vontade, super atenciosos e comunicativos. Procuram sempre por expressões para poder captar fotos lindíssimas.','Dália','Casamento']];
const familyReviews=[['Atenção durante a sessão, paciência para as crianças e rapidez na entrega. As fotos ficaram lindas — a família adorou!','Vânia Lourenço Patrício','Sessão de família'],['Sessões muito divertidas, dinâmicas e com resultados espetaculares. Já fazem parte da nossa vida.','Filipa Rodrigues','Cliente recorrente'],['Estou apaixonada por estas fotografias. Que trabalho incrível.','Cliente CASTA','Maternidade']];
const hero=(title,sub,label)=>`${nav()}<main><section class="hero pagehero">${photo(label)}<div class="hero-copy"><span class="eyebrow">CASTA Histórias</span><h1>${title}</h1><p>${sub}</p></div></section>`;
const home=`<main class="split"><section class="portal"><a class="brand brandtop" href="/">CASTA STUDIO</a><span class="eyebrow">Fotografia & Filme</span><h1>Histórias</h1><p>Fotografia e filme de pessoas, famílias e momentos importantes.</p><a class="btn" href="/historias">Descobrir Histórias</a></section><section class="portal"><a class="brand brandtop" href="/">CASTA STUDIO</a><span class="eyebrow">Imagem para negócios</span><h1>Comercial</h1><p>Fotografia e vídeo para marcas, empresas e negócios.</p><a class="btn" href="/comercial">Descobrir Comercial</a></section></main>`;
const historias=`${nav()}<main><section class="hero">${photo('imagem principal — Histórias')}<div class="hero-copy"><span class="eyebrow">Fotografia & Filme · Alenquer</span><h1>Histórias que merecem ficar.</h1><p>Fotografia e filme de pessoas, relações e tudo aquilo que acontece quando ninguém está preocupado em posar.</p><a class="btn" href="#trabalho">Descobrir o nosso trabalho</a></div></section><section class="intro"><span class="eyebrow">A CASTA</span><div><p class="lead">Somos a Nádia, na fotografia, e o Ruben, no vídeo. Trabalhamos juntos e registamos histórias de forma natural, atentos ao que acontece entre as pessoas — não apenas à câmara.</p></div></section><section class="services" id="trabalho"><article class="service">${photo('Casamento')}<div class="service-copy"><span class="eyebrow">01 · Reportagem</span><h3>Casamentos</h3><p>Fotografia e filme com uma abordagem documental, descontraída e honesta.</p><a class="btn" href="/historias/casamentos">Ver Casamentos</a></div></article><article class="service">${photo('Maternidade e família')}<div class="service-copy"><span class="eyebrow">02 · Pessoas</span><h3>Maternidade & Família</h3><p>Gravidez, newborn, bebés, famílias e todas as pequenas grandes mudanças do primeiro ano.</p><a class="btn" href="/historias/maternidade">Ver Maternidade & Família</a></div></article><article class="service">${photo('Batizado')}<div class="service-copy"><span class="eyebrow">03 · Celebração</span><h3>Batizados</h3><p>Da preparação à celebração: uma reportagem leve, focada na família e em tudo o que acontece à volta.</p><a class="btn" href="/historias/batizados">Ver Batizados</a></div></article></section><section class="section"><span class="eyebrow">Seleção</span><h2>Trabalho recente</h2></section>${gallery()}<section class="section dark about">${photo('Nádia e Ruben — backstage','portrait')}<div><span class="eyebrow">Por trás da CASTA</span><h2>Estamos nós.</h2><p class="lead">Nádia na fotografia. Ruben no vídeo.</p><p>Trabalhamos juntos, discutimos enquadramentos, músicas, edições e provavelmente demasiados detalhes. No dia, queremos sobretudo que as pessoas estejam confortáveis connosco e deixem de pensar que existe uma câmara por perto.</p><a class="btn" href="/historias/sobre">Conhecer a CASTA</a></div></section>${cta('Há uma história por aí que querem guardar?','Falar connosco','/historias/contacto')}</main>${footer()}`;
const wedding=hero('O dia, como ele aconteceu.','Fotografia e filme de casamento com uma abordagem natural e de reportagem. Sem transformar o dia numa produção — nem as pessoas em figurantes.','imagem principal — casamento')+`<section class="intro"><span class="eyebrow">Casamentos</span><div><p class="lead">Há anos que acompanhamos casamentos por dentro: os planos, o nervoso miudinho, as pessoas que chegam de longe e os momentos que não estavam no alinhamento.</p><a class="btn" href="/historias/contacto">Pedir Guia de Casamentos</a></div></section>${gallery(['Preparação','Cerimónia','Retratos','Celebração','Festa'])}<section class="section two"><div><span class="eyebrow">A nossa abordagem</span><h2>Presentes, sem interromper.</h2></div><div><p class="lead">Acompanhamos o dia com atenção ao que é real. Orientamos quando faz falta; no resto do tempo, deixamos acontecer.</p><p>Consoante a coleção, a cobertura pode reunir fotografia, segundo fotógrafo, vídeo, drone, sessão de namoro, galeria privada, filme cinematográfico, conteúdo curto para redes sociais e álbuns.</p></div></section><section class="section dark two"><div><span class="eyebrow">Fotografia + vídeo</span><h2>Uma equipa. Duas formas de ver.</h2></div><div><p class="lead">Nádia fotografa. Ruben filma. Trabalhamos com a mesma linguagem e sem competir pelo mesmo momento.</p></div></section><section class="section"><span class="eyebrow">Do primeiro contacto à entrega</span><div class="steps"><article class="step"><div><h3>Antes do casamento</h3><p>Conversamos, percebemos o ritmo do dia e alinhamos o que é mesmo importante para vocês.</p></div></article><article class="step"><div><h3>Sessão de namoro</h3><p>Quando incluída, é uma boa forma de nos conhecermos — e de perceberem que não é preciso saber posar.</p></div></article><article class="step"><div><h3>No dia</h3><p>A cobertura acompanha os momentos principais e pode estender-se por cerca de 12 a 14 horas, conforme o casamento.</p></div></article><article class="step"><div><h3>Depois</h3><p>As fotografias editadas chegam numa galeria privada; filme e peças físicas seguem a coleção escolhida.</p></div></article></div></section><section class="section faq"><span class="eyebrow">Perguntas frequentes</span><h2>O essencial, antes de falarmos.</h2><details><summary>Como verificamos disponibilidade?</summary><p>Enviem-nos a data, o local e uma ideia do dia. Respondemos com disponibilidade e o guia de coleções.</p></details><details><summary>Como funciona a reserva?</summary><p>Habitualmente é feita com um valor inicial, ficando o restante pagamento para mais perto da data.</p></details><details><summary>Trabalham fora de Alenquer?</summary><p>Sim. Trabalhamos no Oeste, Lisboa e noutras zonas de Portugal, mediante disponibilidade.</p></details></section>${cta('Vamos ver se a data ainda é vossa?','Pedir Guia de Casamentos','/historias/contacto')}</main>${footer()}`;
const maternity=hero('Cada fase tem o seu ritmo.','Sessões de gravidez, newborn, bebés e famílias construídas à volta de quem está diante da câmara.','imagem principal — maternidade')+`<section class="intro"><span class="eyebrow">Maternidade & Família</span><div><p class="lead">Sem fórmulas rígidas. Criamos espaço para estarem juntos e fazemos fotografias que se parecem convosco.</p><a class="btn" href="/historias/contacto">Receber informações e valores</a></div></section><section class="services"><article class="service">${photo('Gravidez')}<div class="service-copy"><span class="eyebrow">28–34 semanas</span><h3>Gravidez</h3><p>Em estúdio, no exterior ou numa combinação dos dois. A janela entre as 28 e as 34 semanas tende a oferecer conforto e uma barriga bem marcada.</p></div></article><article class="service">${photo('Newborn')}<div class="service-copy"><span class="eyebrow">Ao ritmo do bebé</span><h3>Newborn</h3><p>Sessões tranquilas nos primeiros dias ou semanas, com tempo para pausas. Podem incluir pais, irmãos e acessórios simples.</p></div></article><article class="service">${photo('Família')}<div class="service-copy"><span class="eyebrow">Agora</span><h3>Bebés & Famílias</h3><p>Sessões leves e espontâneas, pensadas para a fase em que estão — sem exigir que ninguém se comporte como modelo.</p></div></article><article class="service">${photo('Primeiro aniversário')}<div class="service-copy"><span class="eyebrow">Um ano</span><h3>Primeiro aniversário</h3><p>Uma sessão simples, temática ou Smash the Cake. Também podemos acompanhar diferentes momentos ao longo do primeiro ano.</p></div></article></section>${gallery(['Gravidez','Newborn','Família','Um ano','Acompanhamento'])}${cta('Em que fase estão agora?','Marcar sessão','/historias/contacto')}</main>${footer()}`;
const baptism=hero('Um dia de família.','Fotografia ou fotografia + vídeo, da preparação à celebração, com a cobertura certa para o vosso dia.','imagem principal — batizado')+`<section class="intro"><span class="eyebrow">Batizados</span><div><p class="lead">Há dias em que a cerimónia é só uma parte da história. Registamos a família que se reúne, os pequenos gestos e a celebração sem a tornar numa sessão permanente.</p><a class="btn" href="/historias/contacto">Receber Guia de Batizado</a></div></section>${gallery(['Preparação','Cerimónia','Família','Convidados','Celebração'])}<section class="section two"><div><span class="eyebrow">Cobertura à medida</span><h2>O que faz sentido para o vosso dia.</h2></div><div class="steps"><article class="step"><div><h3>Cerimónia</h3><p>O essencial do batizado, com os momentos da igreja e fotografias de família.</p></div></article><article class="step"><div><h3>Preparação + cerimónia</h3><p>O início do dia, os detalhes escolhidos e a cerimónia.</p></div></article><article class="step"><div><h3>Cerimónia + receção</h3><p>Família, convidados, ambiente, detalhes e o momento do bolo, previamente combinado.</p></div></article><article class="step"><div><h3>Cobertura completa</h3><p>Preparação, cerimónia e receção, em fotografia ou fotografia + vídeo.</p></div></article></div></section>${cta('Querem receber as opções de cobertura?','Receber Guia de Batizado','/historias/contacto')}</main>${footer()}`;
const about=hero('Duas pessoas, uma forma de trabalhar.','A CASTA é a Nádia na fotografia e o Ruben no vídeo. Juntos, trabalhamos com pessoas e com marcas.','Nádia e Ruben')+`<section class="section two"><div><span class="eyebrow">Nádia</span><h2>Fotografia</h2><p class="lead">Repara no gesto, na luz e naquele segundo antes de alguém perceber que está a ser fotografado.</p></div>${photo('Nádia a fotografar','portrait')}</section><section class="section dark two">${photo('Ruben a filmar','portrait')}<div><span class="eyebrow">Ruben</span><h2>Vídeo</h2><p class="lead">Pensa em movimento, som e ritmo. Tem uma relação séria com a edição — e opiniões fortes sobre música.</p></div></section><section class="intro"><span class="eyebrow">CASTA Studio</span><div><p class="lead">Trabalhamos lado a lado, entre histórias pessoais e projetos para empresas. O contexto muda. O cuidado com a imagem, não.</p></div></section>${gallery(['Backstage','Em trabalho','Os dois','Estúdio','Em reportagem'])}${cta('Têm um projeto para nos contar?','Falar connosco','/historias/contacto')}</main>${footer()}`;
const contact=`${nav()}<main><section class="section contact"><div><span class="eyebrow">Contacto</span><h2>Contem-nos o que estão a planear.</h2><p>Digam-nos a data, o lugar e o tipo de sessão. Respondemos com disponibilidade e a informação certa — sem vos enviar um tratado.</p><p>Alenquer, Portugal</p></div><form class="form" id="contact-form"><div class="field"><label for="name">Nome</label><input id="name" name="Nome" required></div><div class="field"><label for="email">Email</label><input id="email" name="Email" type="email" required></div><div class="field"><label for="phone">Telefone / WhatsApp</label><input id="phone" name="Telefone"></div><div class="field"><label for="type">Tipo de sessão</label><select id="type" name="Tipo" required><option value="">Escolher</option><option>Casamento</option><option>Batizado</option><option>Gravidez</option><option>Newborn</option><option>Família</option><option>Primeiro aniversário</option><option>Natal</option><option>Outro</option></select></div><div class="field"><label for="date">Data pretendida</label><input id="date" name="Data" type="date"></div><div class="field"><label for="location">Localização</label><input id="location" name="Localização"></div><div class="field full"><label for="message">Mensagem <span>(opcional)</span></label><textarea id="message" name="Mensagem"></textarea></div><div class="field full"><button class="btn" type="submit">Enviar pedido</button></div><p class="success full" id="success" role="status">Pedido preparado. Nesta demonstração, o formulário ainda não está ligado ao vosso email.</p></form></section></main>${footer()}`;
const commercial=`<div class="nav-reveal-zone" aria-hidden="true"></div><header class="nav dark"><a class="brand brand-logo" href="/" aria-label="CASTA Studio"><img src="/assets/casta-logo-white.png" alt="CASTA"></a><nav class="links"><a href="/historias">Histórias</a><a href="#work">Trabalho</a><a href="#contacto">Contacto</a></nav></header><main class="dark"><section class="hero">${photo('projeto comercial')}<div class="hero-copy"><span class="eyebrow">CASTA Comercial</span><h1>Imagem com trabalho para fazer.</h1><p>Fotografia e vídeo para marcas, empresas e negócios.</p></div></section><section class="intro"><span class="eyebrow">Comercial</span><div><p class="lead">Retratos corporativos, produto, campanhas, conteúdo para redes sociais e vídeo — criados para o contexto onde a imagem vai realmente viver.</p></div></section><section class="section" id="work">${gallery(['Produto','Retrato','Campanha','Conteúdo','Vídeo'])}</section><section class="cta" id="contacto"><h2>Há um projeto para pôr em movimento?</h2><a class="btn" href="/historias/contacto">Falar connosco</a></section></main>${commercialFooter()}`;
const commercialContact=`<div class="nav-reveal-zone" aria-hidden="true"></div><header class="nav dark"><a class="brand brand-logo" href="/" aria-label="CASTA Studio"><img src="/assets/casta-logo-white.png" alt="CASTA"></a><nav class="links" id="links"><a href="/historias">Histórias</a><a href="/comercial">Comercial</a><a href="/comercial/contacto">Contacto</a></nav><button class="menu" aria-expanded="false" aria-controls="links" aria-label="Abrir menu">MENU</button></header><main class="dark"><section class="section contact"><div><span class="eyebrow">Contacto Comercial</span><h2>Fala-nos do teu projeto.</h2><p>Conta-nos o que precisas, onde a imagem vai ser usada e quando gostarias de produzir. Abriremos o WhatsApp Comercial com o pedido completo.</p><p>Alenquer, Portugal</p></div><form class="form" id="contact-form" data-whatsapp="351913415383" data-universe="Comercial"><div class="field"><label for="name">Nome</label><input id="name" name="Nome" required></div><div class="field"><label for="email">Email</label><input id="email" name="Email" type="email" required></div><div class="field"><label for="type">Tipo de projeto</label><select id="type" name="Tipo" required><option value="">Escolher</option><option>Fotografia de produto</option><option>Retrato corporativo</option><option>Espaços / Imobiliário</option><option>Restauração & Hospitality</option><option>Evento</option><option>Vídeo</option><option>Conteúdo para redes sociais</option><option>Outro</option></select></div><div class="field"><label for="date">Data pretendida</label><input id="date" name="Data" type="date"></div><div class="field full"><label for="location">Localização</label><input id="location" name="Localização"></div><div class="field full"><label for="message">O que tens em mente? <span>(opcional)</span></label><textarea id="message" name="Mensagem"></textarea></div><div class="field full"><button class="btn" type="submit">Enviar pelo WhatsApp</button></div><p class="form-note full">Ao continuar, o WhatsApp abre com estes dados numa mensagem. Só será enviada quando confirmares.</p></form></section></main>${commercialFooter()}`;
const pages={'/':home,'/historias':historias,'/historias/casamentos':wedding,'/historias/maternidade':maternity,'/historias/batizados':baptism,'/historias/sobre':about,'/historias/contacto':contact,'/comercial':commercial,'/comercial/contacto':commercialContact};
document.getElementById('app').innerHTML=pages[path]||historias;

// Enrich the service pages with practical information, prices and real client feedback.
const main=document.querySelector('main');
if(path==='/historias') document.querySelector('.about')?.insertAdjacentHTML('beforebegin',testimonials([...weddingReviews.slice(0,1),...familyReviews.slice(0,2)]));
if(path==='/historias/casamentos'){
  document.querySelector('.gallery')?.insertAdjacentHTML('afterend',prices([['Fotografia','1.100 €','Reportagem completa e sessão de namoro.'],['Fotografia + vídeo','2.200 €','Uma equipa, duas formas de contar o dia.']]));
  document.querySelector('.faq')?.insertAdjacentHTML('beforebegin',testimonials(weddingReviews));
  document.querySelectorAll('a[href="/historias/contacto"]').forEach(a=>a.href='/historias/contacto?servico=Casamento');
  document.querySelectorAll('.step p').forEach(p=>{if(p.textContent.includes('galeria privada'))p.textContent='As fotografias editadas chegam numa galeria privada até 2 meses depois. Filme e peças físicas seguem a coleção escolhida.'});
}
if(path==='/historias/maternidade'){
  document.querySelector('.services')?.insertAdjacentHTML('afterend',prices([['Gravidez','110 €','1 hora, 40 fotografias e galeria online.'],['Newborn','160 €','No estúdio ou em casa, ao ritmo do bebé.'],['Primeiro aniversário','150 €','Cenário minimalista ou temático.']]));
  document.querySelector('.cta')?.insertAdjacentHTML('beforebegin',testimonials(familyReviews));
  document.querySelectorAll('a[href="/historias/contacto"]').forEach(a=>a.href='/historias/contacto?servico=Maternidade e Família');
}
if(path==='/historias/batizados'){
  document.querySelector('.gallery')?.insertAdjacentHTML('afterend',prices([['Fotografia','200 €','Cobertura da cerimónia e galeria digital.'],['Fotografia + vídeo','300 €','Cerimónia e vídeo cinematográfico.']]));
  document.querySelectorAll('a[href="/historias/contacto"]').forEach(a=>a.href='/historias/contacto?servico=Batizado');
}
if(path==='/comercial'){
  document.querySelector('.cta .btn')?.setAttribute('href','/comercial/contacto');
  document.querySelector('.links a[href="#contacto"]')?.setAttribute('href','/comercial/contacto');
}

// Turn the Histórias form into a WhatsApp request and remove the redundant phone field.
const form=document.getElementById('contact-form');
if(form&&path==='/historias/contacto'){
  form.dataset.whatsapp='351919592819'; form.dataset.universe='Histórias';
  form.querySelector('#phone')?.closest('.field')?.remove();
  form.querySelector('button').textContent='Enviar pelo WhatsApp';
  form.querySelector('.success')?.remove();
  form.insertAdjacentHTML('beforeend','<p class="form-note full">Ao continuar, o WhatsApp abre com estes dados numa mensagem. Só será enviada quando confirmares.</p>');
}
const requestedService=new URLSearchParams(location.search).get('servico');
if(requestedService&&form?.querySelector('#type')){
  const select=form.querySelector('#type');
  let option=[...select.options].find(o=>o.textContent===requestedService);
  if(!option){ option=new Option(requestedService,requestedService); select.add(option); }
  select.value=option.value;
}
document.querySelector('.menu')?.addEventListener('click',e=>{const open=document.getElementById('links').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('links')?.classList.remove('open');document.querySelector('.menu')?.setAttribute('aria-expanded','false')}});
form?.addEventListener('submit',e=>{
  e.preventDefault();
  if(!form.reportValidity())return;
  const data=new FormData(form); const greeting=form.dataset.universe==='Comercial'?'Olá Ruben,':`Olá, CASTA ${form.dataset.universe}!`; const lines=[greeting,`Chamo-me ${data.get('Nome')}.`,`Gostaria de pedir informações sobre: ${data.get('Tipo')}.`];
  if(data.get('Data'))lines.push(`Data pretendida: ${data.get('Data')}.`);
  if(data.get('Localização'))lines.push(`Localização: ${data.get('Localização')}.`);
  if(data.get('Email'))lines.push(`Email: ${data.get('Email')}.`);
  lines.push('',String(data.get('Mensagem')||''));
  window.open(`https://wa.me/${form.dataset.whatsapp}?text=${encodeURIComponent(lines.join('\n'))}`,'_blank','noopener,noreferrer');
});

// Active navigation state and page-specific search metadata.
document.querySelectorAll('.links a').forEach(a=>{if(new URL(a.href,location.origin).pathname.replace(/\/$/,'')===path)a.setAttribute('aria-current','page')});
const meta={
  '/historias':['Fotografia de Casamentos e Famílias em Alenquer | CASTA','Fotografia e filme de casamentos, maternidade, famílias e batizados em Alenquer.'],
  '/historias/casamentos':['Fotógrafos de Casamento em Alenquer | CASTA','Reportagem de casamento natural em fotografia e vídeo. Coleções desde 1.100 €.'],
  '/historias/maternidade':['Fotografia de Gravidez, Newborn e Família | CASTA','Sessões de gravidez, recém-nascido, bebés e famílias em Alenquer. Valores desde 110 €.'],
  '/historias/batizados':['Fotografia e Vídeo de Batizados em Alenquer | CASTA','Cobertura de batizados em fotografia e vídeo, desde a cerimónia ao dia completo.'],
  '/historias/contacto':['Marcar Sessão | CASTA Histórias','Pede disponibilidade e informações para a tua sessão através do WhatsApp.'],
  '/comercial':['Fotografia e Vídeo para Empresas | CASTA Comercial','Fotografia de produto, retrato, espaços, eventos e vídeo para empresas e marcas.'],
  '/comercial/contacto':['Contactar | CASTA Comercial','Fala-nos do teu projeto de fotografia, vídeo ou conteúdo para marcas.']
};
if(meta[path]){document.title=meta[path][0];document.querySelector('meta[name="description"]')?.setAttribute('content',meta[path][1])}
const siteNav=document.querySelector('.nav');
if(siteNav){
  let lastScroll=window.scrollY;
  let topHover=false;
  const reveal=()=>siteNav.classList.remove('nav-hidden');
  const conceal=()=>{if(window.scrollY>90&&!topHover)siteNav.classList.add('nav-hidden')};
  window.addEventListener('scroll',()=>{const current=window.scrollY;if(current<90||current<lastScroll)reveal();else if(current>lastScroll)conceal();lastScroll=current},{passive:true});
  document.querySelector('.nav-reveal-zone')?.addEventListener('mouseenter',()=>{topHover=true;reveal()});
  siteNav.addEventListener('mouseenter',()=>{topHover=true;reveal()});
  siteNav.addEventListener('mouseleave',()=>{topHover=false;conceal()});
}
